# needed for push operation (with new digest) to test-upload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc
  labels:
    app: picalc
    test-upload: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picalc
  template:
    metadata:
      labels:
        app: picalc
        test-upload: "true"
    spec:
      containers:
        - name: picalc
          image: gcr.io/cluster-01-271319/picalc@sha256:2d5a6dba01b6e82a1d5ed7fa949cacab2ae0be2ba736be2f496f2648b9c9f0b0
          resources:
            requests:
              cpu: 100m
              memory: 50M
            limits:
              cpu: 200m
              memory: 80M
          ports:
            - name: http-server
              containerPort: 8080
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "cat /proc/1/status"]
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: picalc
  labels:
    app: picalc
    test-upload: "true"
spec:
  ports:
    - port: 8080
      targetPort: http-server
  selector:
    app: picalc
  type: LoadBalancer
  template:
    metadata:
      labels:
        test-upload: "true"
