apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc
  labels:
    app: picalc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picalc
  template:
    metadata:
      labels:
        app: picalc
        test-upload: "true"
        date: 2026-03-11_13-53-16
    spec:
      containers:
        - name: picalc
          image: gcr.io/cluster-01-290863/picalc@sha256:e770b0a796cb9a71db6b094ea48a264e8da8b16994f0b2f40d546c67c81e3357
          resources:
            requests:
              cpu: 100m
              memory: 50M
            limits:
              cpu: 200m
              memory: 80M
          ports:
            - name: http-server
              containerPort: 8080
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "cat /proc/1/status"]
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: picalc
  labels:
    app: picalc
spec:
  ports:
    - port: 8080
      targetPort: http-server
  selector:
    app: picalc
  type: LoadBalancer
---

